### ISSUE TITLE
How many training steps do you use when training on GQA-Inpaint?

### ISSUE THREAD

**Issue by jianzongwu** [abyildirim/inst-inpaint#10]
I cannot find the total training steps you used in the config or the code.
There seems to be no description about the training steps or epochs in the paper either.
Could you tell me how many training steps do you use in the GQA-Inpaint dataset?
And does training longer or shorter influence the results? What is the influence?

Thanks!

**Comment by abyildirim** [comment]
Hi, we have provided the training details in Table 1:

<img src="https://github.com/abyildirim/inst-inpaint/assets/49433632/b4e509c7-f981-44e7-8542-fc479b7f8c70"  width="350">

The GQA-Inpaint model is trained for 300 epochs. We observed that the results converged around 300 epochs but didn't experiment with much longer training.
