### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by LQ971225** [abyildirim/inst-inpaint#11]
Hello, why can't I download the dataset? It says "no permission" halfway through the download.

**Comment by abyildirim** [comment]
Hi, it can be due to Google Drive restrictions. As an alternative, you can try to download the dataset from the Hugging Face link: [GQA-Inpaint Dataset](https://huggingface.co/datasets/abyildirim/gqa-inpaint/blob/main/gqa-inpaint.zip)

**Comment by LQ971225** [comment]
Hello, thank you for your response. I'm sorry for replying just now. I've given up on reproducing this article; it's too difficult (a great article). You can close the question now.
