### ISSUE TITLE
About the scale of the GQA-inpainting dataset

### ISSUE THREAD

**Issue by MichaelHL-ai** [abyildirim/inst-inpaint#8]
In the paper, it said "Because from source images we pick different objects and generate instructions, training includes 173715 unique source-target-prompt pairs. We test the models on 4811 unique source images, 9485 unique target images, and 18883 unique source-target-prompt pairs.". When I downloaded the data from github, I got 38w+ masks, which means I have 38w+ source-target-mask pairs. Did I process the data in a wrong way or something?

**Comment by abyildirim** [comment]
Hi, there should be 66014 folders in the mask and the inpainted image files. The prompts for the scenes are generated in the provided dataset class randomly by using the object attributes in the scene files. Therefore, there can be multiple prompts generated for the same scene and the same object. You can use the dataset configs in the config file to have an identical dataset with our experiments if the folder number is consistent.

**Comment by MichaelHL-ai** [comment]
Thanks for your reply. I see the difference now. You filtered out some masks that shouldn't have been used, but I considered all of the mask images. Am I right?

**Comment by MichaelHL-ai** [comment]
> Hi, there should be 66014 folders in the mask and the inpainted image files. The prompts for the scenes are generated in the provided dataset class randomly by using the object attributes in the scene files. Therefore, there can be multiple prompts generated for the same scene and the same object. You can use the dataset configs in the config file to have an identical dataset with our experiments if the folder number is consistent.

When I use gqa_inpainting.py script on test_scenes.json, I got 10811 lines same as test_instructions.json file, and on train_scenes.json len(GQAInpaintBase) = 100098.

**Comment by abyildirim** [comment]
Yes, the images and masks are being filtered according to the provided scene JSON file. The lengths of the datasets seem correct.  When the test_instructions.json file is provided, in the test dataset config, the instructions are fixed therefore there are 10811 pairs in total. In the training and validation datasets, the instructions are randomly generated. This is why the total number of possible pairs is higher than the length of the datasets.
