### ISSUE TITLE
Upload dataset to huggingface

### ISSUE THREAD

**Issue by Zeqiang-Lai** [abyildirim/inst-inpaint#9]
Could you upload the dataset to huggingface as well ? The google drive always complains "there are too many users ..." and we could not download it.

**Comment by abyildirim** [comment]
Hi, the dataset and the model have already been uploaded to Hugging Face. You can download them from the following links: 
| [GQA-Inpaint Dataset](https://huggingface.co/datasets/abyildirim/gqa-inpaint/blob/main/gqa-inpaint.zip) | [GQA-Inpaint Model](https://huggingface.co/abyildirim/inst-inpaint-models/blob/main/gqa_inpaint.zip) |

**Comment by Zeqiang-Lai** [comment]
Thanks!
